name: AgentPlusCoaching
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6081822081468999
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#3a4450'
    - '#f6782e'
    - '#b9bcc1'
    - '#888d94'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.375
  rhythmicContrast: 0.941652616718784
purpose: []
